language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

jobs:
  include:
    - stage: test
      php: 7.2
      env: WP_VERSION=latest
      script:
        - bash ./tests/bin/install_wp_tests.sh mobile_contact_bar_test root '' localhost $WP_VERSION
        - export PATH="$HOME/.composer/vendor/bin:$PATH"
        - composer global require "phpunit/phpunit=6.*"
        - WP_MULTISITE=0 phpunit
        - WP_MULTISITE=1 phpunit

    - stage: test
      php: 5.6
      script:
        - composer install
        - ./vendor/bin/phpcs -p --standard=phpcs.xml.dist ./includes ./tests/*.php ./*.php

notifications:
  email:
    on_success: never
    on_failure: change
