language: php

sudo: false

cache:
  directories:
    - $HOME/.npm
    - $HOME/.composer/cache
    - vendor

before_install:
  - nvm install && nvm use
  - npm install npm -g

jobs:
  include:
    - stage: test
      script:
        - npm install
        - npm run ci

    - stage: test
      php: 5.6
      script:
        - composer install
        - vendor/bin/phpcs -p --standard=phpcs.xml.dist ./includes ./tests/*.php ./*.php

    - stage: test
      php: 7.2
      env: WP_VERSION=latest
      script:
        - bash tests/bin/install_wp_tests.sh mobile_contact_bar_test root '' localhost $WP_VERSION
        - export PATH="$HOME/.composer/vendor/bin:$PATH"
        - composer global require "phpunit/phpunit=6.*"
        - WP_MULTISITE=0 phpunit
        - WP_MULTISITE=1 phpunit

notifications:
  email:
    on_success: never
    on_failure: change
